# $Id$

ADDITIONAL_LIB_DIRS += \
	-L./Backend/$(GNUSTEP_OBJ_DIR) \
	-L./Frontend/$(GNUSTEP_OBJ_DIR)

ADDITIONAL_TOOL_LIBS += \
        -lZideStoreBackend      \
        -lZideStoreFrontend     \
	\
	-lLSFoundation	\
	-lGDLAccess	\
        \
	-lNGiCal	\
	-lNGScripting	\
	-lNGLdap -lNGMime -lNGExtensions -lEOControl	\
	-lXmlRpc -lDOM -lSaxObjC

# for osx
#	-lcrypt

ADDITIONAL_INCLUDE_DIRS += -I. -I./Frontend -I./Backend
