# $Id: GNUmakefile.preamble 15 2004-08-21 03:22:17Z helge $

ADDITIONAL_BUNDLE_LIBS += \
	-lOGoProject -lOGoAccounts -lOGoDocuments -lOGoBase \
	-lNGExtensions

ADDITIONAL_LIB_DIRS += 				\
	-L../../../DocumentAPI/OGoBase/$(GNUSTEP_OBJ_DIR)	\
	-L../../../DocumentAPI/OGoAccounts/$(GNUSTEP_OBJ_DIR)

ADDITIONAL_CFLAGS += -Wall
