# compilation settings

ADDITIONAL_BUNDLE_LIBS += \
	-lOGoProject -lOGoAccounts -lOGoDocuments -lOGoBase \
	-lNGExtensions

ADDITIONAL_LIB_DIRS += \
	-L../../../DocumentAPI/OGoBase/$(GNUSTEP_OBJ_DIR)	\
	-L../../../DocumentAPI/OGoAccounts/$(GNUSTEP_OBJ_DIR)

ADDITIONAL_CFLAGS += -Wall
