# $Id$

include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME = Persons

Persons_OBJC_FILES = \
	SxPersonFolder.m	\
	SxGroupFolder.m		\
	SxPerson.m		\
	\
	SxVCardPersonRenderer.m	\

ADDITIONAL_INCLUDE_DIRS += -I.. -I../../..

include $(GNUSTEP_MAKEFILES)/subproject.make
