# $Id: GNUmakefile 1 2004-08-20 11:17:52Z znek $

include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME = Companies

Companies_OBJC_FILES = \
	SxEnterpriseFolder.m			\
	SxEnterprise.m				\
	\
	SxVCardEnterpriseRenderer.m		\

ADDITIONAL_INCLUDE_DIRS += -I.. -I../../..

include $(GNUSTEP_MAKEFILES)/subproject.make
