# $Id: GNUmakefile.preamble 1 2004-08-20 11:17:52Z znek $

ADDITIONAL_INCLUDE_DIRS += \
	-I..			\
	-I../OGoFoundation	\

ADDITIONAL_WOBUNDLE_LIBS += \
	-lOGoFoundation	\
	-lLSSearch -lLSFoundation \
	-lNGObjWeb \
	-lDOM -lSaxObjC

ADDITIONAL_BUNDLE_LIBS += $(ADDITIONAL_WOBUNDLE_LIBS)

ADDITIONAL_LIB_DIRS += -L../../OGoFoundation/$(GNUSTEP_OBJ_DIR)

ifeq ($(FOUNDATION_LIB),nx)
ADDITIONAL_BUNDLE_LIBS += -lFoundationExt
ADDITIONAL_LDFLAGS += -framework Foundation
endif
