# GNUstep makefile

-include ../config.make
include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS = \
	PPSync		\
	OGoPalm		\
	OGoNHSSync	\
	OGoPalmUI	\
	OGoPalmWebUI	\

include $(GNUSTEP_MAKEFILES)/aggregate.make
