# $Id$

skytrackd_TOOL_LIBS += \
	-lOGoDaemon -lXmlSchema	\
	-lLSFoundation		\
	-lSxComponents -lNGObjWeb		\
	-lOGoDatabaseProject -lOGoProject	\
	-lEOControl	\
	-lNGExtensions	\

ifeq ($(FOUNDATION_LIB),nx)
ADDITIONAL_TOOL_LIBS += -lFoundationExt
ADDITIONAL_LDFLAGS += -framework Foundation
endif
