# $Id$

include ../common.make

TOOL_NAME = skymaild

# Sources

skymaild_OBJC_FILES = \
	skymaild.m		\
	Application.m		\
	Session.m		\
	DirectAction.m		\
	DirectAction+Mail.m	\
	Filter.m		\
	FilterEntry.m		\
	SieveManager.m		\

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/tool.make
-include GNUmakefile.postamble
