# $Id: GNUmakefile 1 2004-08-20 11:17:52Z znek $

include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME = Groups

Groups_OBJC_FILES = \

ADDITIONAL_INCLUDE_DIRS += -I.. -I../../..

include $(GNUSTEP_MAKEFILES)/subproject.make
