# $Id: GNUmakefile.preamble 1 2004-08-20 11:17:52Z znek $

OGoMailViewers_WOBUNDLE_LIBS += \
	-lOGoFoundation		\
	-lNGScripting		\
	-lNGMime		\
	-lEOControl		\
	-lDOM -lSaxObjC

ADDITIONAL_BUNDLE_LIBS += $(OGoMailViewers_WOBUNDLE_LIBS)
