# GNUstep makefile

-include ../../config.make
include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS = \
	LSWScheduler		\
	OGoResourceScheduler	\
	OGoScheduler		\
	OGoSchedulerDock	\
	OGoSchedulerViews	\

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
-include GNUmakefile.postamble
