# GNUstep makefile

include ../../config.make
include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS = \
	AddressUI	\
	PersonsUI	\
	EnterprisesUI	\
	LDAPAccounts	\

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
-include GNUmakefile.postamble
