# $Id: GNUmakefile.preamble 1 2004-08-20 11:17:52Z znek $

OGoROOT=../..

ADDITIONAL_INCLUDE_DIRS += -I. -I.. -I./Contacts/

ADDITIONAL_INCLUDE_DIRS += \
	-I$(OGoROOT)/Logic/LSFoundation/

libZideStoreFrontend_LIBRARIES_DEPEND_UPON += \
        -lZideStoreBackend      \
	-lLSFoundation	        \
	-lNGObjWeb -lNGScripting\
	-lNGiCal -lNGMime -lNGStreams -lNGExtensions -lEOControl	\
	-lXmlRpc -lDOM -lSaxObjC

libZideStoreFrontend_LIB_DIRS += \
	-L../ZSBackend/$(GNUSTEP_OBJ_DIR)
