# postprocessing

$(RESOURCES_DIR) :
	$(MKDIRS) $(RESOURCES_DIR)

zidestore-resources : $(RESOURCES_DIR) $(libZSFrontend_RESOURCES)
	@(if [ "$(libZSFrontend_RESOURCES)" != "" ]; then \
	  echo "Copying resources into install path ..."; \
          for ff in $(libZSFrontend_RESOURCES); do \
	    cp $$ff $(RESOURCES_DIR)/$$ff; \
          done; \
	fi)

after-install :: zidestore-resources
