# $Id$

include ../common.make

WOBUNDLE_NAME = RelatedLinksUI

RelatedLinksUI_PRINCIPAL_CLASS = RelatedLinksUI

RelatedLinksUI_OBJC_FILES = \
	RelatedLinksUI.m	\
	OGoObjectLinkList.m	\

RelatedLinksUI_RESOURCE_FILES += \
	Version			\
	Defaults.plist		\
	\
	OGoObjectLinkList.wox	\

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/wobundle.make
-include GNUmakefile.postamble
