# $Id$

GNUSTEP_INSTALLATION_DIR = $(GNUSTEP_LOCAL_ROOT)

include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS =  \
	LSInvoice	\
	SkyInvoiceLib	\
	SkyInvoice	\

include $(GNUSTEP_MAKEFILES)/aggregate.make
