# $Id: GNUmakefile.preamble 1 2004-08-20 11:17:52Z znek $

OGoROOT=../..

ADDITIONAL_INCLUDE_DIRS += \
	-I. -I..	\
	-I./Contacts/	\

ADDITIONAL_INCLUDE_DIRS += -I$(OGoROOT)/Logic

libZideStoreBackend_LIBRARIES_DEPEND_UPON += \
	-lLSFoundation	\
	-lGDLAccess	\
	-lNGExtensions -lEOControl \
	-lDOM
