# compilation settings

OGoROOT=../../..


ADDITIONAL_INCLUDE_DIRS += -I. -I.. -I../..
ADDITIONAL_INCLUDE_DIRS += -I$(OGoROOT)/Logic -I../../SoObjects

ADDITIONAL_LIB_DIRS += \
	-L../../SoObjects/ZSTasks/$(GNUSTEP_OBJ_DIR) \
	\
	-L../../ZSFrontend/$(GNUSTEP_OBJ_DIR) \
	-L../../ZSBackend/$(GNUSTEP_OBJ_DIR)

RSS_BUNDLE_LIBS += -lNGObjWeb -lZSBackend

SYSTEM_LIB_DIR += $(CONFIGURE_SYSTEM_LIB_DIR)
