# $Id$

include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME = XmlRpcCoding

XmlRpcCoding_OBJC_FILES = \
	SkyAccountDocument+XmlRpcCoding.m	\
	SkyAddressDocument+XmlRpcCoding.m	\
	SkyAppointmentDocument+XmlRpcCoding.m	\
	SkyCompanyDocument+XmlRpcCoding.m	\
	SkyDocument+XmlRpcCoding.m		\
	SkyEnterpriseDocument+XmlRpcCoding.m	\
	SkyJobDocument+XmlRpcCoding.m		\
	SkyPersonDocument+XmlRpcCoding.m	\
	SkyProject+XmlRpcCoding.m		\
	SkyTeamDocument+XmlRpcCoding.m

ADDITIONAL_INCLUDE_DIRS += -I.. 

include $(GNUSTEP_MAKEFILES)/subproject.make
