# GNUstep makefile

-include ../../../config.make
include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME = Actions

Actions_OBJC_FILES = \
	DirectAction.m			\
	DirectAction+Account.m		\
	DirectAction+Appointment.m	\
	DirectAction+Generic.m		\
	DirectAction+Defaults.m		\
	DirectAction+Enterprise.m	\
	DirectAction+Fault.m		\
	DirectAction+Job.m		\
	DirectAction+Mails.m		\
	DirectAction+Person.m		\
	DirectAction+Project.m		\
	DirectAction+Resource.m		\
	DirectAction+System.m		\
	DirectAction+Team.m		\
	DirectAction+Link.m		\
	\
	SkyAppointmentQualifier+XmlRpc.m

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/subproject.make
-include GNUmakefile.postamble
