# compilation settings

OGoROOT=../..

ADDITIONAL_INCLUDE_DIRS += -I. -I..

ADDITIONAL_INCLUDE_DIRS += -I$(OGoROOT)/Logic/

ADDITIONAL_LIB_DIRS += \
	-L../ZSFrontend/$(GNUSTEP_OBJ_DIR) \
	-L../ZSBackend/$(GNUSTEP_OBJ_DIR)

PrefsUI_BUNDLE_LIBS += \
	-lZSBackend \
	-lGDLAccess \
	-lNGObjWeb  \
	-lNGMime -lNGStreams -lNGExtensions -lEOControl \
	-lXmlRpc -lDOM -lSaxObjC

SYSTEM_LIB_DIR += $(CONFIGURE_SYSTEM_LIB_DIR)
