# $Id$

include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS = \
	Common		\
	Scheduler	\
	Projects

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
-include GNUmakefile.postamble
