# $Id: GNUmakefile 1 2004-08-20 11:17:52Z znek $

include ../common.make

SUBPROJECT_NAME = Mails

Mails_OBJC_FILES = \
	SxDraftsFolder.m	\
	SxOutboxFolder.m	\
	SxSentFolder.m		\
	SxTrashFolder.m		\

ADDITIONAL_INCLUDE_DIRS += -I..

include $(GNUSTEP_MAKEFILES)/subproject.make
