# compilation settings

LSWScheduler_WOBUNDLE_LIBS += \
	-lOGoScheduler -lOGoSchedulerTools -lOGoDocuments \
	-lNGiCal	\
	-lGDLAccess	\
	-lDOM -lSaxObjC

ADDITIONAL_BUNDLE_LIBS += $(LSWScheduler_WOBUNDLE_LIBS)
