# $Id: GNUmakefile.preamble 1 2004-08-20 11:17:52Z znek $

ADDITIONAL_LIB_DIRS += \
	-L../ZSBackend/$(GNUSTEP_OBJ_DIR) \
	-L../ZSFrontend/$(GNUSTEP_OBJ_DIR)

ADDITIONAL_TOOL_LIBS += \
        -lZSBackend	\
        -lZSFrontend	\
	-lLSFoundation	\
	-lGDLAccess	\
	-lNGiCal	\
	-lNGScripting	\
	-lNGLdap -lNGMime -lNGExtensions -lEOControl	\
	-lXmlRpc -lDOM -lSaxObjC

# for OSX
#	-lcrypt
