.TH ogo-zidestore 8 "October 2004" OpenGroupware.org "User Manuals"
.\" Copyright (c) 2004 Helge Hess. All rights reserved.
.\" ====================================================================
.\"
.\" Copyright (c) 2000-2004 Helge Hess.  All rights reserved.
.\"
.\" Check the COPYING file for further information.
.\"
.\" Created with the help of:
.\"   http://www.schweikhardt.net/man_page_howto.html
.\"

.SH NAME
ogo-zidestore-1.3 \- OGo native client integration server
.SH SYNOPSIS
.B ogo-zidestore-1.3 
[
.BI \-WOPort " port"
]

.SH DESCRIPTION
.B ogo-zidestore-1.3
is the server used to connect the OpenGroupware.org database and functionality
to native clients like Mozilla Calendar, Evolution, Kontact, Outlook or
Apple iCal.app.
.PP
Note that you should not connect
.B ogo-zidestore-1.3
directly on its port using your client, but rather use
.B mod_ngobjweb
in combination with
.B Apache.

.SH OPTIONS
.TP 12
.IP "-WOPort port"
This option sets the TCP/IP port the
.B ogo-zidestore-1.3
server is running on and which the mod_ngobjweb will connect to.

.SH FILES
.I /etc/opengroupware.org/NSGlobalDomain.plist
.RS
This file contains configurations which apply to all OpenGroupware.org
related daemons. This includes settings like the database connection
dictionary or the path where preferences of OGo accounts are stored.
.RE
.I /etc/opengroupware.org/ogo-zidestore-1.3.plist
.RS
Configurations contained in this file overwrite those in the NSGlobalDomain.
You can persist any command line option in this file using the
.BR Defaults (5)
tool.
.RE

.SH BUGS
ZideStore bugs are collected in the OpenGroupware.org Bugzilla:
  http://bugzilla.opengroupware.org/

.SH AUTHOR
Helge Hess <helge.hess@opengroupware.org>

.SH SEE ALSO
.BR httpd (8),
.BR ogo-webui (8),
.BR ogo-xmlrpcd (8),
.BR Defaults (5).

.SH HISTORY
The ZideStore server first appeared as an extension to the SKYRiX 
web groupware 4.1. It finally transformed the SKYRiX server from a
pure web application server to a general purpose groupware server
supporting a large set of native clients and standard protocols.
