# compilation settings

ADDITIONAL_WOBUNDLE_LIBS += \
	-lOGoDocuments	\
	-lOGoScheduler -lOGoSchedulerTools	\
	-lOGoContacts -lOGoAccounts \
	-lNGiCal	\
	-lGDLAccess	\
	-lNGLdap	\
	-lDOM -lSaxObjC

ADDITIONAL_BUNDLE_LIBS += $(ADDITIONAL_WOBUNDLE_LIBS)
