# $Id$

include ../common.make

SUBPROJECT_NAME = Mails

Mails_OBJC_FILES = \
	SxDraftsFolder.m	\
	SxOutboxFolder.m	\
	SxSentFolder.m		\
	SxTrashFolder.m		\

ADDITIONAL_INCLUDE_DIRS += -I..

include $(GNUSTEP_MAKEFILES)/subproject.make
