# $Id: GNUmakefile.preamble 1 2004-08-20 11:17:52Z znek $

Contacts_BUNDLE_LIBS += \
        -lZSFrontend -lZSBackend \
	-lGDLAccess \
        -lNGObjWeb -lNGScripting \
	-lNGMime -lNGStreams -lNGExtensions -lEOControl \
	-lXmlRpc -lDOM -lSaxObjC
