# $Id: GNUmakefile.preamble 1 2004-08-20 11:17:52Z znek $

USED_LIBS = \
        -lZSFrontend -lZSBackend\
	-lGDLAccess		\
        -lNGObjWeb		\
	-lNGMime		\
	-lNGStreams -lNGExtensions -lEOControl \
	-lXmlRpc -lDOM -lSaxObjC

libZSContacts_LIBRARIES_DEPEND_UPON += $(USED_LIBS)

Contacts_BUNDLE_LIBS += $(USED_LIBS) -lZSContacts
