# compilation settings

USED_LIBS = \
        -lZSFrontend -lZSBackend\
	-lGDLAccess		\
        -lNGObjWeb		\
	-lNGMime		\
        -lNGiCal                \
	-lNGStreams -lNGExtensions -lEOControl \
	-lXmlRpc -lDOM -lSaxObjC

libZSContacts_LIBRARIES_DEPEND_UPON += $(USED_LIBS)

Contacts_BUNDLE_LIBS += $(USED_LIBS) -lZSContacts
