# compilation settings

ADDITIONAL_CPPFLAGS += -Wall

OGoMailFilter_INCLUDE_DIRS += -I. -I.. -I../..

OGoMailFilter_WOBUNDLE_LIBS += \
	-lOGoWebMail	\
	-lOGoFoundation	\
	-lNGMime -lEOControl \
	-lDOM -lSaxObjC

ADDITIONAL_LIB_DIRS += \
	-L../OGoWebMail/$(GNUSTEP_OBJ_DIR)

ADDITIONAL_BUNDLE_LIBS += $(OGoMailFilter_WOBUNDLE_LIBS)
