# $Id$

OGoROOT   =../..
WebUIROOT =..

ADDITIONAL_BUNDLE_LIBS += \
	-lGDLAccess	\
	-lNGScripting	\
	-lDOM -lSaxObjC

ADDITIONAL_LIB_DIRS += \
	-L$(OGoROOT)/DocumentAPI/OGoDocuments/$(GNUSTEP_OBJ_DIR)
