# $Id: GNUmakefile.preamble 12 2004-08-21 02:22:09Z helge $

OGoROOT   =../..
WebUIROOT =..

ADDITIONAL_BUNDLE_LIBS += \
	-lGDLAccess	\
	-lNGMime	\
	-lDOM -lSaxObjC

ADDITIONAL_LIB_DIRS += \
	-L$(OGoROOT)/DocumentAPI/OGoDocuments/$(GNUSTEP_OBJ_DIR)
