# $Id: GNUmakefile.preamble 1 2004-08-20 11:17:52Z znek $

ZIDESTORE=../..

ADDITIONAL_INCLUDE_DIRS += \
	-I. \
	-I$(ZIDESTORE)/Products	\
	-I$(ZIDESTORE)/Frontend	\
	-I$(ZIDESTORE)/Backend	\
	-I$(ZIDESTORE)

# explicit dependencies for Mach linker
ProjectsUI_BUNDLE_LIBS += \
	-lNGObjWeb \
	-lNGMime -lNGStreams -lNGExtensions -lEOControl	\
	-lXmlRpc -lDOM -lSaxObjC
