# ZideStore protocols makefile

-include ../../config.make
include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS += \
	EvoConnect	\
	WCAP		\
	RSS		\

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
-include GNUmakefile.postamble
