# compilation settings

OGoROOT   =../..
WebUIROOT =..

ADDITIONAL_WOBUNDLE_LIBS += \
	-lOGoJobs -lOGoDocuments\
	-lGDLAccess	\
	-lDOM -lSaxObjC

ADDITIONAL_BUNDLE_LIBS += $(ADDITIONAL_WOBUNDLE_LIBS)

JobUI_INCLUDE_DIRS += -IHeaders

ADDITIONAL_LIB_DIRS += \
	-L$(OGoROOT)/DocumentAPI/OGoDocuments/$(GNUSTEP_OBJ_DIR)	\
	-L$(OGoROOT)/DocumentAPI/OGoJobs/$(GNUSTEP_OBJ_DIR)
