# $Id: GNUmakefile.preamble 1 2004-08-20 11:17:52Z znek $

USED_LIBS = \
        -lZSFrontend -lZSBackend \
	-lGDLAccess \
        -lNGObjWeb -lNGScripting \
	-lNGMime -lNGStreams -lNGExtensions -lEOControl \
	-lXmlRpc -lDOM -lSaxObjC

libZSTasks_LIBRARIES_DEPEND_UPON += $(USED_LIBS)

Tasks_BUNDLE_LIBS += $(USED_LIBS) -lZSTasks
