# $Id$

include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME = Groups

Groups_OBJC_FILES = \
	SxGroupsFolder.m\
	SxGroup.m	\

ADDITIONAL_INCLUDE_DIRS += -I.. -I../../..

include $(GNUSTEP_MAKEFILES)/subproject.make
