# $Id$

include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME = Appointments

Appointments_OBJC_FILES = \
	SxEvoAptQueryInfo.m		\
	SxAppointmentFolder+Evo.m	\

ADDITIONAL_INCLUDE_DIRS += \
	-I. -I.. -I../..		\
	-I../../Products/Appointments	\
	-I../../Frontend		\
	-I../../Backend			\

include $(GNUSTEP_MAKEFILES)/subproject.make
