# GNUstep makefile

-include ../config.make
include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS += OGoModel


-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
-include GNUmakefile.postamble
