# $Id$

include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS += 		\
	XmlSchema	\
	OGoIDL		\
	OGoDaemon	\
			\
	skymasterd	\
	skyregistryd	\
	skyaccountd	\
	skycontactd	\
	skyaptd		\
	skydbd		\
	skyjobd		\
	skymaild	\
	skytrackd	\
	skysystemd	\
	skyobjinfod	\

#	skysoapproxyd	\

include $(GNUSTEP_MAKEFILES)/aggregate.make
