# $Id$

include ../common.make

TOOL_NAME = skysoapproxyd

# Sources

skysoapproxyd_OBJC_FILES =	\
	skysoapproxyd.m		\
	Application.m		\
	SkySoapProxyAction.m	\

# Libraries

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/tool.make
-include GNUmakefile.postamble
