# $Id$

after-OGoScheduler-all ::
	@(cd $(BUNDLE_NAME)$(BUNDLE_EXTENSION);\
	  $(LN_S) -f ../bundle-info.plist .)

$(RESOURCES_DIR) :
	$(MKDIRS) $(RESOURCES_DIR)


ogosched-resources : $(RESOURCES_DIR) $(libOGoScheduler_RESOURCES)
	@(if [ "$(libOGoScheduler_RESOURCES)" != "" ]; then \
	echo "Copying resources into install path ..."; \
	for ff in $(libOGoScheduler_RESOURCES); do \
	cp $$ff $(RESOURCES_DIR)/$$ff; \
	done; \
	fi)

after-install :: ogosched-resources
