# $Id$

include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS = \
	BaseUI		\
	OGoUIElements	\
	PropertiesUI	\
	RelatedLinksUI	\

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
-include GNUmakefile.postamble
