# $Id: GNUmakefile.preamble 1 2004-08-20 11:17:52Z znek $

OGoMailEditor_INCLUDE_DIRS += -I. -I.. -I../..

OGoMailEditor_WOBUNDLE_LIBS += \
	-lOGoFoundation	\
	-lNGScripting	\
	-lNGMime -lEOControl \
	-lDOM -lSaxObjC

ADDITIONAL_BUNDLE_LIBS += $(OGoMailEditor_WOBUNDLE_LIBS)
