# $Id$

include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME = OGoClient

OGoClient_OBJC_FILES = \
	OGoClientConnection.m		\
	OGoClientManager.m		\
	OGoXmlRpcDataSource.m		\
	OGoClientProjectDataSource.m	\

ADDITIONAL_INCLUDE_DIRS += -I..

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/subproject.make
-include GNUmakefile.postamble
