# GNUstep makefile

include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS += \
	OGoDocuments		\
	OGoRawDatabase		\

SUBPROJECTS += \
	OGoAccounts		\
	OGoContacts		\
	OGoBase			\
	OGoProject		\
	OGoDatabaseProject	\
	OGoFileSystemProject	\
	OGoJobs			\
	OGoScheduler		\

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
-include GNUmakefile.postamble
