# $Id: GNUmakefile.preamble 1 2004-08-20 11:17:52Z znek $

ADDITIONAL_WOBUNDLE_LIBS += \
	-lOGoDocuments	\
	-lOGoScheduler -lOGoSchedulerTools	\
	-lOGoContacts -lOGoAccounts \
	-lGDLAccess	\
	-lNGLdap	\
	-lDOM -lSaxObjC

ADDITIONAL_BUNDLE_LIBS += $(ADDITIONAL_WOBUNDLE_LIBS)
