# $Id$

include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME = ModelClasses

ModelClasses_OBJC_FILES = \
	LSAddress.m			\
	LSCompanyAssignment.m		\
	LSCompanyCategory.m		\
	LSCompanyInfo.m			\
	LSCompanyValue.m		\
	LSAppointment.m			\
	LSAppointmentResource.m		\
	LSDateCompanyAssignment.m	\
	LSDateInfo.m			\
	LSDoc.m				\
	LSDocumentEditing.m		\
	LSDocumentVersion.m		\
	LSEmail.m			\
	LSEmailContent.m		\
	LSEmailFolder.m			\
	LSEnterprise.m			\
	LSJob.m				\
	LSJobHistory.m			\
	LSJobHistoryInfo.m		\
	LSNewsArticle.m			\
	LSNewsArticleLink.m		\
	LSNote.m			\
	LSPerson.m			\
	LSProject.m			\
	LSProjectCompanyAssignment.m	\
	LSStaff.m			\
	LSTeam.m			\
	LSTelephone.m			\
	LSTrust.m			\
	LSUrl.m				\
	LSUrlCriterion.m	  	\
	LSUrlRating.m			\
	LSLog.m				\
	LSInvoice.m			\
	LSArticle.m			\
	LSArticleUnit.m			\
	LSArticleCategory.m		\
	LSInvoiceArticleAssignment.m	\
	LSResource.m                    \
	LSResourceAssignment.m          \
	LSJobResourceAssignment.m       \
	LSJobAssignment.m               \
	LSProjectInfo.m                 \
	LSSessionLog.m			\
	LSInvoiceAccount.m		\
	LSInvoiceAccounting.m		\
	LSInvoiceAction.m		\
	LSEvent.m			\

ADDITIONAL_INCLUDE_DIRS += -I../Headers/ -I..

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/subproject.make
-include GNUmakefile.postamble
