# $Id$

libOGoPalm_LIBRARIES_DEPEND_UPON += \
	-lOGoContacts			\
	-lOGoJobs			\
	-lOGoRawDatabase		\
	-lOGoSchedulerTools		\
	-lOGoScheduler

OGoPalmDS_LIB_DIRS    += -L./$(GNUSTEP_OBJ_DIR)
OGoPalmDS_BUNDLE_LIBS += -lOGoPalm

ADDITIONAL_OBJCFLAGS    += -Wall
ADDITIONAL_INCLUDE_DIRS += -I.
