# $Id: GNUmakefile.preamble 1 2004-08-20 11:17:52Z znek $

OGoWebMail_INCLUDE_DIRS += -I. -I.. -I../..

OGoWebMail_WOBUNDLE_LIBS += \
	-lOGoWebMail	\
	-lOGoFoundation	\
	-lNGMime -lEOControl \
	-lDOM -lSaxObjC

libOGoWebMail_LIBRARIES_DEPEND_UPON += \
	-lOGoFoundation	\
	-lNGMime -lEOControl \
	-lDOM -lSaxObjC

ADDITIONAL_BUNDLE_LIBS += $(OGoWebMail_WOBUNDLE_LIBS)

ADDITIONAL_LIB_DIRS += -L./$(GNUSTEP_OBJ_DIR)
