# $Id$

include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS = \
	Appointments	\
	Contacts	\
	Tasks		\
	Projects	\

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
-include GNUmakefile.postamble
