# $Id$

include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS = \
	LSWMail		\
	OGoWebMail	\
	OGoMailInfo	\
	OGoMailViewers	\

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
-include GNUmakefile.postamble
