# GNUstep makefile

include ../../config.make
include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS = \
	LSWMail		\
	OGoWebMail	\
	OGoMailInfo	\
	OGoMailViewers	\
	OGoMailEditor	\
	OGoMailFilter	\
	OGoRecipientLists

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
-include GNUmakefile.postamble
