# $Id: GNUmakefile 1 2004-08-20 11:17:52Z znek $

include ../common.make

SUBPROJECT_NAME = Persons

Persons_OBJC_FILES = \
	SxPersonFolder.m	\
	SxGroupFolder.m		\
	SxPerson.m		\
	\
	SxVCardPersonRenderer.m	\

ADDITIONAL_INCLUDE_DIRS += -I../Contacts/

include $(GNUSTEP_MAKEFILES)/subproject.make
