# postprocessing

$(RESOURCES_DIR) :
	$(MKDIRS) $(RESOURCES_DIR)

zidestore-resources : $(RESOURCES_DIR) $(libZSBackend_RESOURCES)
	@(if [ "$(libZSBackend_RESOURCES)" != "" ]; then \
	  echo "Copying resources into install path ..."; \
          for ff in $(libZSBackend_RESOURCES); do \
	    cp $$ff $(RESOURCES_DIR)/`basename $$ff`; \
          done; \
	fi)

after-install :: zidestore-resources
