# $Id$

include $(GNUSTEP_MAKEFILES)/common.make

COMMAND_BUNDLE = LSInvoice

LSInvoice_OBJC_FILES =      \
	LSNewInvoiceCommand.m		\
	LSSetInvoiceCommand.m		\
	LSNewInvoiceArticleCommand.m	\
	LSSetInvoiceArticleCommand.m	\
	LSSetArticleCategoryCommand.m	\
	LSNewArticleCategoryCommand.m	\
	LSSetInvoiceAssignmentCommand.m	\
	LSGetInvoiceArticlesCommand.m	\
	LSDeleteInvoiceCommand.m	\
	LSDeleteInvoiceArticleCommand.m	\
	LSDeleteArticleCategoryCommand.m\
	LSDeleteArticleUnitCommand.m	\
	LSPrintInvoiceCommand.m		\
	LSCancelInvoiceCommand.m	\
	LSInvoiceMonitionCommand.m	\
	LSFinishInvoiceCommand.m	\
	LSCopyInvoicesCommand.m		\
	LSMoveInvoicesCommand.m		\
	LSNewInvoiceArticleAssignmentCommand.m	\
	LSSetInvoiceArticleAssignmentCommand.m	\
	LSGetInvoiceArticleCommand.m	\
	LSGetInvoiceCommand.m		\
	LSFetchUnsettledInvoicesCommand.m	\
	LSGetEnterpriseWithInvoiceStatus.m	\
	LSFetchAdditionalInvoiceValuesCommand.m	\
	LSGetInvoiceAccountCommand.m		\
	LSNewInvoiceAccountCommand.m		\
	LSSetInvoiceAccountCommand.m		\
	LSGetInvoiceActionCommand.m		\
	LSNewInvoiceActionCommand.m		\
	LSGetInvoiceAccountingCommand.m		\
	LSNewInvoiceAccountingCommand.m		\
	LSFetchInvoiceIntoInvoiceAccountingCommand.m	\
	LSCreateInvoiceAccountCommand.m		\
	LSPrintInvoiceMonitionCommand.m		\
	LSCreateInvoiceAccountForEnterpriseCommand.m	\
	LSInvoiceAccountingCommand.m		\
	LSGetInvoicesForGlobalIDs.m		\

include ../commandbundle.make
