# $Id$

ADDITIONAL_INCLUDE_DIRS += -I. -I..

ADDITIONAL_LIB_DIRS += \
	-L../OGoConfigGen/$(GNUSTEP_OBJ_DIR)

ADDITIONAL_BUNDLE_LIBS += \
        -lOGoConfigGen  \
	-lNGScripting	\
	-lGDLAccess	\
	-lDOM -lSaxObjC
