.TH ogo-webui 8 "October 2004" OpenGroupware.org "User Manuals"
.\" Copyright (c) 2004 Helge Hess. All rights reserved.
.\" ====================================================================
.\"
.\" Copyright (c) 2004 Helge Hess.  All rights reserved.
.\"
.\" Check the COPYING file for further information.
.\"
.\" Created with the help of:
.\"   http://www.schweikhardt.net/man_page_howto.html
.\"

.SH NAME
ogo-webui-1.0 \- OGo HTML interface server
.SH SYNOPSIS
.B ogo-webui-1.0 
[
.BI \-WOPort " port"
]

.SH DESCRIPTION
.B ogo-webui-1.0
is the server which provides the HTML interface of OpenGroupware.org.
.PP
Note that you should not connect
.B ogo-webui-1.0
directly on its port using your browser, but rather use
.B mod_ngobjweb
in combination with
.B Apache.
Please see the installation instructions for further information.

.SH OPTIONS
.TP 12
.IP "-WOPort port"
This option sets the TCP/IP port the
.B ogo-webui-1.0
server is running on and which the mod_ngobjweb will connect to.

.SH FILES
.I /etc/opengroupware.org/NSGlobalDomain.plist
.RS
This file contains configurations which apply to all OpenGroupware.org
related daemons. This includes settings like the database connection
dictionary or the path where preferences of OGo accounts are stored.
.RE
.I /etc/opengroupware.org/ogo-webui-1.0.plist
.RS
Configurations contained in this file overwrite those in the NSGlobalDomain.
You can persist any command line option in this file using the
.BR Defaults (5)
tool.
.RE

.SH BUGS
Bugs are collected in the OpenGroupware.org Bugzilla:
  http://bugzilla.opengroupware.org/

.SH AUTHOR
Helge Hess <helge.hess@opengroupware.org>

.SH SEE ALSO
.BR httpd (8),
.BR ogo-zidestore (8),
.BR ogo-xmlrpcd (8),
.BR Defaults (5).

.SH HISTORY
The OpenGroupware.org server is a direct descendant of the SKYRiX web
groupware 4.1 which was released under the GPL/LGPL in Juli 2003.
