# GNUstep Makefile

include $(GNUSTEP_MAKEFILES)/common.make

WOAPP_NAME = OpenGroupware10a

OpenGroupware10a_OBJC_FILES = \
	OpenGroupware.m			\
	OpenGroupware+CTI.m		\
	OGoLogoutPage.m			\
	Main.m				\
	DirectAction.m			\
	WODirectAction+LoginAction.m	\
	SoOGoAuthenticator.m

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/woapp.make
-include GNUmakefile.postamble
