# $Id: GNUmakefile.postamble 1 2004-08-20 11:17:52Z znek $

before-all :: $(OpenGroupware10a_DERIVED_RESOURCES)

before-install :: $(OpenGroupware10a_DERIVED_RESOURCES)

clean ::
	rm -f $(OpenGroupware10a_DERIVED_RESOURCES)
