# $Id$

include ../common.make

SUBPROJECT_NAME = Appointments

Appointments_OBJC_FILES = \
	SxAptManager.m		\
	SxAptSetHandler.m	\
	SxAptSetIdentifier.m	\
	SxAptManager+iCal.m	\
	\
	SxAppointmentRenderer.m	\

include $(GNUSTEP_MAKEFILES)/subproject.make
