# $Id: GNUmakefile.preamble 1 2004-08-20 11:17:52Z znek $

Appointments_BUNDLE_LIBS += \
        -lZSFrontend -lZSBackend \
	-lGDLAccess \
        -lNGObjWeb -lNGScripting \
	-lNGiCal -lNGMime -lNGStreams -lNGExtensions -lEOControl\
	-lXmlRpc -lDOM -lSaxObjC
