#!/bin/sh
set -e

. /usr/share/debconf/confmodule

# Only act on a fresh install
db_get opengroupware.org/autoconfigure || true

if [ "$1" = configure ] && [ -z "$2" ] && [ ! "$DEBCONF_RECONFIGURE" ] && [ "$RET" = "true" ]; then
	if ! /usr/sbin/ogo-create-instance -d; then
		echo
		echo "Warning: Automatic setup of an OpenGroupware.org instance has failed."
		echo "Use ogo-create-instance to manually setup an instance."
		echo
	fi
fi

exit 0
