# $Id: GNUmakefile 1 2004-08-20 11:17:52Z znek $

include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS = \
	ZSAppointments	\
	ZSContacts	\
	ZSTasks		\
	ZSProjects	\

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
-include GNUmakefile.postamble
