# GNUstep makefile

include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS = \
	ZSCommon	\
	ZSAppointments	\
	ZSContacts	\
	ZSTasks		\
	ZSProjects	\

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
-include GNUmakefile.postamble
