# $Id: GNUmakefile.preamble 1 2004-08-20 11:17:52Z znek $

EnterprisesUI_RESOURCE_FILES += Defaults.plist Version

ADDITIONAL_WOBUNDLE_LIBS += \
	-lOGoFoundation \
	-lOGoDocuments -lOGoContacts -lLSFoundation \
	-lGDLAccess	\
	-lNGMime	\
	-lNGExtensions -lEOControl \
	-lDOM -lSaxObjC

ADDITIONAL_BUNDLE_LIBS += $(ADDITIONAL_WOBUNDLE_LIBS)
