# $Id$

include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS += \
	OGoFoundation		\
	OpenGroupware.org	\
	Common			\
	Contact			\
	PreferencesUI		\
	AdminUI			\
	JobUI 			\
	NewsUI			\
	Scheduler		\
	Mailer			\
	Project			\
	SoOGo			\

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
-include GNUmakefile.postamble
