# GNUstep makefile

include ../config.make
include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS += \
	OGoFoundation		\
	Main			\
	Common			\
	Contact			\
	GroupsUI		\
	PreferencesUI		\
	AdminUI			\
	JobUI 			\
	NewsUI			\
	Scheduler		\
	Mailer			\
	Project			\
	SoOGo			\
	Resources		\
	Templates		\
	CTI/AsteriskDialer	\
	CTI/STLIDialer		\

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
-include GNUmakefile.postamble
