# $Id: GNUmakefile.preamble 315 2004-09-25 16:51:37Z helge $

ifneq ($(GNUSTEP_BUILD_DIR),)
	RELBUILD_DIR_libSOGoCommonUI = $(GNUSTEP_OBJ_DIR)
else
	RELBUILD_DIR_libSOGoCommonUI = $(GNUSTEP_OBJ_DIR)
endif

libSOGoUI_LIBRARIES_DEPEND_UPON += \
	-lNGObjWeb	\
	-lNGMime	\
	-lNGStreams -lNGExtensions -lEOControl \
	-lXmlRpc -lDOM -lSaxObjC

