# compilation settings

OGoROOT=../../..


ADDITIONAL_INCLUDE_DIRS += -I. -I.. -I../..
ADDITIONAL_INCLUDE_DIRS += -I$(OGoROOT)/Logic


ADDITIONAL_LIB_DIRS += \
	-L../../ZSFrontend/$(GNUSTEP_OBJ_DIR) \
	-L../../ZSBackend/$(GNUSTEP_OBJ_DIR)

SYSTEM_LIB_DIR += -L/usr/local/lib -L/usr/lib

WCAP_BUNDLE_LIBS += -lNGObjWeb
