# compilation settings

OGoWebMail_INCLUDE_DIRS += -I. -I.. -I../..

OGoWebMail_WOBUNDLE_LIBS += \
	-lOGoWebMail	\
	-lOGoFoundation	\
	-lNGMime	\
	-lNGExtensions -lEOControl \
	-lDOM -lSaxObjC

libOGoWebMail_LIBRARIES_DEPEND_UPON += \
	-lOGoFoundation	\
	-lNGMime	\
	-lNGStreams -lNGExtensions -lEOControl \
	-lDOM -lSaxObjC

ADDITIONAL_BUNDLE_LIBS += $(OGoWebMail_WOBUNDLE_LIBS)

ADDITIONAL_LIB_DIRS += -L./$(GNUSTEP_OBJ_DIR)
