# $Id$

include ../common.make

SUBPROJECT_NAME = Contacts

Contacts_OBJC_FILES = \
	SxContactManager.m			\
	SxContactManager+evo.m			\
	SxContactSQLQuery.m			\
	SxEvoContactSQLQuery.m			\
	SxZLContactSQLQuery.m			\
	SxListContactSQLQuery.m			\
	SxContactEmailSQLQuery.m		\
	\
	SxFetchContact.m			\
	SxFetchEnterprise.m			\
	SxFetchPerson.m				\
	SxFetchGroup.m				\
	\
	SxUpdateContact.m			\
	SxUpdateEnterprise.m			\
	SxUpdatePerson.m			\
	\
	SxContactSetIdentifier.m		\
	\
	NSMutableDictionary+SetSafeObject.m	\

include $(GNUSTEP_MAKEFILES)/subproject.make
