# compilation settings

#
# This file is used to specify settings for the compilation process. It is
# a seperate file so that the main makefile isn't cluttered by infrastructure
# stuff.
#

ADDITIONAL_LIB_DIRS += -L/usr/local/lib -L/usr/lib
