# installation

$(RESOURCES_DIR) :
	$(MKDIRS) $(RESOURCES_DIR)
	$(MKDIRS) $(RESOURCES_DIR)/schemes

ngobjweb-resources : $(RESOURCES_DIR) $(libXmlSchema_RESOURCES)
	@(if [ "$(libXmlSchema_RESOURCES)" != "" ]; then \
	  echo "Copying resources into install path ..."; \
          for ff in $(libXmlSchema_RESOURCES); do \
	    cp $$ff $(RESOURCES_DIR)/$$ff; \
          done; \
	fi)

after-install :: ngobjweb-resources
