# $Id$

ADDITIONAL_INCLUDE_DIRS += -I.. -I../..

ADDITIONAL_LIB_DIRS += \
	-L$(GNUSTEP_OBJ_DIR)

libXmlSchema_LIBRARIES_DEPEND_UPON += -lSaxObjC

createSchemaClasses_TOOL_LIBS += -lXmlSchema -lSaxObjC

xschema_TOOL_LIBS += -lSaxObjC -lXmlSchema
