# $Id$

include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS = \
	OGoNote			\
	OGoProject		\
	OGoProjectInfo		\
	OGoDocInlineViewers	\
	OGoProjectZip		\
	LSWProject		\

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
-include GNUmakefile.postamble
