# $Id$

include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = skysoapd soapclient soapTest

skysoapd_OBJC_FILES = \
	SOAPDirectAction.m		\
	SOAPDirectAction+WSDL.m		\
	Application.m			\
	DirectAction.m			\
	skysoapd.m			\

soapclient_OBJC_FILES = \
	soapclient.m

soapTest_OBJC_FILES = \
	soapTest.m

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/tool.make
-include GNUmakefile.postamble
