# $Id$

include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME = Actions

Actions_OBJC_FILES = \
	DirectAction.m			\
	DirectAction+Account.m		\
	DirectAction+Defaults.m		\
	DirectAction+Fault.m		\
	DirectAction+Team.m		\

ADDITIONAL_INCLUDE_DIRS += -I.. 

include $(GNUSTEP_MAKEFILES)/subproject.make
