#
#  GNUmakefile
#  ÇPROJECTNAMEÈ
#
#  Created by ÇFULLUSERNAMEÈ on ÇDATEÈ.
#  Copyright (c) ÇYEARÈ ÇORGANIZATIONNAMEÈ. All rights reserved.
#

include $(GNUSTEP_MAKEFILES)/common.make

WOAPP_NAME = ÇPROJECTNAMEÈ

ÇPROJECTNAMEÈ_OBJC_FILES = \
ÇPROJECTNAMEÈ_main.m	Application.m	Session.m 	DirectAction.m	\
Main.m

ÇPROJECTNAMEÈ_COMPONENTS = \
Main.wo

ÇPROJECTNAMEÈ_RESOURCE_FILES = \

ÇPROJECTNAMEÈ_WEBSERVER_RESOURCE_FILES := $(shell find WebServerResources -type f -print)

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/woapp.make
-include GNUmakefile.postamble
