# $Id: GNUmakefile.preamble 1 2004-08-20 11:17:52Z znek $

OGoROOT=../..


ADDITIONAL_INCLUDE_DIRS += -I. -I..

ADDITIONAL_INCLUDE_DIRS += -I$(OGoROOT)/Logic/

ADDITIONAL_LIB_DIRS += \
	-L../ZSFrontend/$(GNUSTEP_OBJ_DIR) \
	-L../ZSBackend/$(GNUSTEP_OBJ_DIR)

SYSTEM_LIB_DIR += -L/usr/local/lib -L/usr/lib

PrefsUI_BUNDLE_LIBS += \
	-lZSBackend \
	-lGDLAccess \
	-lNGObjWeb  \
	-lNGMime -lNGStreams -lNGExtensions -lEOControl \
	-lXmlRpc -lDOM -lSaxObjC
