name: Build and Test

on:
  push:
  pull_request:
  schedule:
    - cron: "20 15 * * 1"

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - ubuntu:noble
    container: ${{ matrix.image }}
    steps:
      - name: Checkout SOPE Repository
        uses: actions/checkout@v4
        with:
          repository: OpenGroupware/SOPE
          ref: refs/heads/develop
          path: SOPE-develop
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Update APT and Install Cache Deps
        run:  |
          apt-get -y -qq update
          apt-get -y -qq install \
            libxml2-dev libldap2 libldap-dev libpq-dev libpq5 \
            libmemcached-dev libmemcached-tools libcurl4-openssl-dev \
            libcrypt-dev make libz-dev gobjc \
            gnustep-make gnustep-base-runtime libgnustep-base-dev
      - name: Configure and install SOPE
        run:  |
          ls
          ls ..
          ls ../..
          cd SOPE-develop
          ./configure \
          --with-gnustep \
          --enable-debug \
          --disable-strip \
          --enable-xml \
          --enable-postgresql \
          --enable-openldap \
          --with-ssl=ssl
          make -j 8 all
          make install
      - name: Configure OGo
        run:          
          ./configure \
            --with-gnustep \
            --gsmake=/usr/share/GNUstep/Makefiles \
            --enable-debug \
            --disable-strip
      - name: Build OGo
        run: make -j 8 all
