# GNUstep makefile

-include ../../config.make
include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS = \
	OGoConfigGen	\
	ogocfggen	\
	ConfigAdminUI	\
	CyrusAdminUI	\

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
-include GNUmakefile.postamble
